import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'main3.dart';
void main() {
  runApp(const Main2());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Main2 extends StatelessWidget {
  const Main2({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Page(),
        ]),
      ),
    );
  }
}

class DietPlan {
  final String date;
  final String time;
  final String description;
  final String imageUrl;

  DietPlan({required this.date, required this.time, required this.description, required this.imageUrl});

  factory DietPlan.fromJson(Map<String, dynamic> json) {
    return DietPlan(
      date: json['date'] as String,
      time: json['time'] as String,
      description: json['description'] as String,
      imageUrl: json['imageUrl'] as String,
    );
  }
}

Future<List<DietPlan>> fetchDietPlans() async {
  final response = await http.get(Uri.parse('http://your-backend-server.com/diet-plans'));

  if (response.statusCode == 200) {
    List jsonResponse = json.decode(response.body);
    return jsonResponse.map((item) => DietPlan.fromJson(item)).toList();
  } else {
    throw Exception('Failed to load diet plans from server');
  }
}

Future<void> addDietPlan(DietPlan dietPlan) async {
  final response = await http.post(
    Uri.parse('http://your-backend-server.com/diet-plans'),
    headers: <String, String>{
      'Content-Type': 'application/json; charset=UTF-8',
    },
    body: jsonEncode(<String, String>{
      'date': dietPlan.date,
      'time': dietPlan.time,
      'description': dietPlan.description,
      'imageUrl': dietPlan.imageUrl,
    }),
  );

  if (response.statusCode != 200) {
    throw Exception('Failed to add diet plan to server');
  }
}


class Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 850,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFFF9F9F9)),
          child: Stack(
            children: [
              Positioned(
                top: 63,  // 체중관리 줄의 위치에 따라 조정해야 합니다.
                left: 10.0,  // 왼쪽 끝에 배치하기 위해 0으로 설정.
                child: IconButton(
                  icon: Icon(Icons.arrow_back),
                  iconSize: 24,  // 아이콘 크기를 24로 설정.
                  color: Colors.black,
                  onPressed: () {
                    // Main2에서 Main3 페이지로 이동

                    Navigator.pushReplacement(
                      context,
                      MaterialPageRoute(builder: (context) => Main3()),
                    );
                  }
                ),
              ),
              Positioned(
                left: 35,
                top: 70,
                child: SizedBox(
                  width: 324,
                  height: 38.49,
                  child: Text(
                    '내 식단 작성',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black.withOpacity(0.800000011920929),
                      fontSize: 20,
                      fontFamily: 'Montserrat',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 77,
                child: Container(
                  width: 24,
                  height: 24,
                  padding: const EdgeInsets.symmetric(horizontal: 7.75, vertical: 4.25),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [

                    ],
                  ),
                ),
              ),
              Positioned(
                left: 46,
                top: 154,
                child: Container(
                  width: 302,
                  height: 408.50,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 0.50, color: Color(0xFF868686)),
                      borderRadius: BorderRadius.circular(30),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x0C000000),
                        blurRadius: 64,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 46,
                top: 582.50,
                child: Container(
                  width: 302,
                  height: 56,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 302,
                          height: 56,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(width: 0.50, color: Color(0xFF868686)),
                              borderRadius: BorderRadius.circular(30),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x0C000000),
                                blurRadius: 64,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 84,
                        top: 15,
                        child: Container(
                          width: 137,
                          height: 24,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  padding: const EdgeInsets.all(2),
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 20,
                                        height: 20,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 1.2,
                                              child: Container(
                                                width: 20,
                                                height: 20,
                                                decoration: ShapeDecoration(
                                                  shape: OvalBorder(
                                                    side: BorderSide(
                                                      width: 1,
                                                      strokeAlign: BorderSide.strokeAlignCenter,
                                                      color: Colors.black.withOpacity(0.6000000238418579),
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 29,
                                top: 7,
                                child: SizedBox(
                                  width: 128,
                                  height: 24,
                                  child: GestureDetector( // GestureDetector 위젯을 사용합니다.
                                    onTap: () {
                                      Navigator.push(
                                        context,
                                        MaterialPageRoute(builder: (context) => Main3()),
                                      );
                                    },
                                  child: Text(
                                    '식단 추가하기',
                                    style: TextStyle(
                                      color: Colors.black.withOpacity(0.699999988079071),
                                      fontSize: 16,
                                      fontFamily: 'Montserrat',
                                      fontWeight: FontWeight.w500,
                                      height: 1,
                                    ),
                                  ),
                                ),
                              ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              // ... 이전 코드 생략 ...

              Positioned(
                left: 46,
                top: 650,  // '식단 추가하기' 버튼 아래에 위치하도록 top 값을 조정합니다.
                child: FutureBuilder<List<DietPlan>>(
                  future: fetchDietPlans(),
                  builder: (context, snapshot) {
                    if (snapshot.hasData) {
                      return ListView.builder(
                        itemCount: snapshot.data!.length,
                        itemBuilder: (context, index) {
                          return ListTile(
                            title: Text(snapshot.data![index].description),
                            subtitle: Text(snapshot.data![index].date + ' ' + snapshot.data![index].time),
                            leading: Image.network(snapshot.data![index].imageUrl),
                          );
                        },
                      );
                    } else if (snapshot.hasError) {
                      return Text('${snapshot.error}');
                    }
                    return const CircularProgressIndicator();
                  },
                ),
              ),

// ... 이후 코드 생략 ...

              Positioned(
                left: 118,
                top: 586,
                child: IconButton(  // IconButton 위젯을 추가합니다.
                  icon: Icon(Icons.add),  // '+' 아이콘을 추가합니다.
                  iconSize: 20,  // 아이콘 크기를 24로 설정.
                  color: Colors.black,
                  onPressed:() {
                  //   // '+' 버튼을 눌렀을 때의 동작을 정의합니다.
                  },
                ),
              ),
              Positioned(
                left: 0,
                top: 114,
                child: Container(
                  width: 398,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Colors.black.withOpacity(0.20000000298023224),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 140,
                top: 192,
                child: SizedBox(
                  width: 114,
                  height: 31,
                  child: Text(
                    '2023 - 11 - 08',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Montserrat',
                      fontWeight: FontWeight.w500,
                      height: 0.07,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 139,
                top: 201,
                child: Container(
                  width: 104,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 115,
                top: 222.50,
                child: SizedBox(
                  width: 164,
                  height: 21,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: '식사 시간 ',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 15,
                            fontFamily: 'Montserrat',
                            fontWeight: FontWeight.w500,
                            height: 0,
                          ),
                        ),
                        TextSpan(
                          text: '08 : 49 ',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 10,
                            fontFamily: 'Montserrat',
                            fontWeight: FontWeight.w500,
                            height: 0,
                          ),
                        ),
                      ],
                    ),
                    textAlign: TextAlign.center,
                  ),
                ),
              ),
              Positioned(
                left: 73,
                top: 457.50,
                child: Container(
                  width: 247,
                  height: 81,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0x9E3C3C3C)),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 80,
                top: 461,
                child: SizedBox(
                  width: 234,
                  height: 74,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: '오늘 아침은 든든하게 현미밥,된장시락국 메인으로 반찬 6가지랑 먹었는데 점심까지 혈당도 안정적이였고, 든든하게 시작할 수 있어서 좋았다. \n',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 10,
                            fontFamily: 'Montserrat',
                            fontWeight: FontWeight.w500,
                            height: 0.18,
                          ),
                        ),
                        TextSpan(
                          text: '( 일기 느낌 )',
                          style: TextStyle(
                            color: Colors.black.withOpacity(0.4000000059604645),
                            fontSize: 10,
                            fontFamily: 'Montserrat',
                            fontWeight: FontWeight.w500,
                            height: 0.18,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 73,
                top: 248.50,
                child: Container(
                  width: 247,
                  height: 185,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/247x185"),
                      fit: BoxFit.contain,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}